### PR TITLE
Initial README

### PR DESCRIPTION
**Pull request by danwalkercode**

### CODE REVIEW

**Comment by danwalkercode** [comment]
Fixes #1

**Comment by sibidass** [comment]
Thanks @iDemonix This is addressed in another PR

**Comment by danwalkercode** [comment]
No worries @sibidass, mine does have some extra info in it though so feel free to add it if you want!

**Comment by sibidass** [comment]
@iDemonix Thanks! This codebase is supposed to work slightly different. It need to be installed as a aws lambda and should be subscribed to sns topic, so that notifications to that topic will be send as sms to twilio segment. I have to make some more modifications for seamless integration, after which the usage can be updated.

**Pull request closed without merging**
